package CurrConvertApp;

/**
* CurrConvertApp/CurrConvertHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from currconvert.idl
* Tuesday, September 15, 2020 9:46:47 AM SGT
*/

public final class CurrConvertHolder implements org.omg.CORBA.portable.Streamable
{
  public CurrConvertApp.CurrConvert value = null;

  public CurrConvertHolder ()
  {
  }

  public CurrConvertHolder (CurrConvertApp.CurrConvert initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CurrConvertApp.CurrConvertHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CurrConvertApp.CurrConvertHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CurrConvertApp.CurrConvertHelper.type ();
  }

}
