package CurrConvertApp;


/**
* CurrConvertApp/CurrConvertOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from currconvert.idl
* Tuesday, September 15, 2020 9:46:47 AM SGT
*/

public interface CurrConvertOperations 
{
  String getSymbols ();
  boolean symbolExist (String symbol);
  String convertAll (String base);
  String convertAllWithAmount (double amount, String base);
  String convertSome (String base, String target);
  String convertSomeWithAmount (double amount, String base, String target);
  String displaySymbols ();
  void shutdown ();
} // interface CurrConvertOperations
