package CurrConvertApp;


/**
* CurrConvertApp/CurrConvert.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from currconvert.idl
* Tuesday, September 15, 2020 9:46:47 AM SGT
*/

public interface CurrConvert extends CurrConvertOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CurrConvert
